package qa.learning;// Generated by Selenium IDE
import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

public class CreateContactTest extends TestBase {

  @Test
  public void createContact() {
    initContactCreation();
    fillContactForm(new ContactData("Contactname", "Contactsurname", "world", "+79113332255", "test@mail.test"));
    submitContactCreation();
    gotoHomePage();
  }

}
