package qa.learning.tests;// Generated by Selenium IDE


import org.junit.Test;
import qa.learning.model.ContactData;
import java.util.Set;
import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.MatcherAssert.*;


public class CreateContactTest extends TestBase {

  @Test
  public void testCreateContact() {
    app.goTo().homePage();
    Set<ContactData> before = app.contact().all();
    ContactData contact = new ContactData()
            .withFirstName("Contactname").withLastName("Contactsurname").withAddress("world").withPhoneMobile("+79113332255").withEmail("test@mail.test");
    app.contact().create(contact);
    Set<ContactData> after = app.contact().all();
    assertThat(before.size() + 1, equalTo(after.size()));
    contact.withId(after.stream().mapToInt((c) -> c.getId()).max().getAsInt());
    before.add(contact);
    assertThat(before, equalTo(after));
  }




}
